# Generated by Django 4.2.7 on 2024-03-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
