# Generated by Django 4.2.7 on 2024-03-23 05:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_slug_categories_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[578, 324], upload_to=''),
        ),
    ]
