# Generated by Django 4.2.7 on 2024-04-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_onsale',
        ),
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
