services:
  db:
    image: postgres:13 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    volumes:
      - ./:/core
      - static_volume:/core/staticfiles
      - media_volume:/core/media
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    environment:
      - DOCKER_ENV=1
    depends_on:  
      - db
      - redis

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/core/staticfiles
      - media_volume:/core/media
    depends_on:
      - web

  celery_worker:
    build: .
    command: celery -A online_shop worker --loglevel=info
    env_file:
      - .env.docker
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: