services:
  db:
    image: postgres:13 
    environment:
      - POSTGRES_DB=market
      - POSTGRES_USER=shop_admin
      - POSTGRES_PASSWORD=1029384756
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://shop_admin:1029384756@db:5432/market
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:  
      - db

volumes:
  postgres_data:
  redis_data: