services:
  db:
    image: postgres:13 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - ./:/core
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:  
      - db
      - redis

volumes:
  postgres_data:
  redis_data: